runtime: nodejs20

handlers:
- url: /(.*\..+)$ 
  static_files: dist/kramviweb/browser/\1
  upload: dist/kramviweb/browser/(.*\..+)$

- url: /.*
  secure: always
  static_files: dist/kramviweb/browser/index.html
  upload: dist/kramviweb/browser/index.html